CREATE TABLE PACIENTE (
    COD_PAC SERIAL PRIMARY KEY,
    CPF TEXT UNIQUE NOT NULL,
    NOME TEXT NOT NULL,
    CONTATO TEXT,
    ENDERECO TEXT
);

CREATE TABLE MEDICAMENTO (
    COD_MED SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL,
    BULA TEXT
);

CREATE TABLE ITEM_MED (
	COD_ITEM_MED INT NOT NULL,
	COD_MED INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY (COD_ITEM_MED, COD_MED)
);

CREATE TABLE CARGO (
    COD_CARGO SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL,
    SALARIO NUMERIC(10, 2) NOT NULL
);

CREATE TABLE FUNCIONARIO (
    COD_FUNC SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL,
    CPF TEXT UNIQUE NOT NULL,
    COD_CARGO INT,
    FOREIGN KEY (COD_CARGO) REFERENCES CARGO(COD_CARGO)
);

CREATE TABLE SERVICO (
    COD_SERVICO SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT,
    PRECO NUMERIC(10, 2) NOT NULL
);

CREATE TABLE MEDICO (
    CRM INT PRIMARY KEY,
    NOME TEXT NOT NULL,
    CPF TEXT UNIQUE NOT NULL,
	CONTATO TEXT NOT NULL,
	ENDERECO TEXT NOT NULL
);

CREATE TABLE SUPERVISAO (
    COD_SUPERVISAO SERIAL PRIMARY KEY,
    COD_SUPERVISOR INT,
    COD_SUPERVISIONA INT,
    FOREIGN KEY (COD_SUPERVISOR) REFERENCES MEDICO(CRM),
    FOREIGN KEY (COD_SUPERVISIONA) REFERENCES MEDICO(CRM)
);

CREATE TABLE PLANO (
    COD_PLANO SERIAL PRIMARY KEY,
    NOME TEXT NOT NULL,
    VALOR_CON NUMERIC(10, 2)NOT NULL,
    VALOR_INT NUMERIC(10, 2) NOT NULL
);


CREATE TABLE PROCEDIMENTO (
    COD_PROCED SERIAL PRIMARY KEY,
    COD_FUNC INT,
    COD_SERVICO INT,
    COD_PAC INT,
    DT_ATEND DATE NOT NULL,
    VALOR NUMERIC(10, 2) NOT NULL,
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
    FOREIGN KEY (COD_SERVICO) REFERENCES SERVICO(COD_SERVICO),
    FOREIGN KEY (COD_PAC) REFERENCES PACIENTE(COD_PAC)
);

CREATE TABLE CONSULTA (
    COD_CONSUL SERIAL PRIMARY KEY,
    COD_PAC INT,
    CRM INT,
	COD_PLANO INT,
    MOTIVO TEXT NOT NULL,
    DT_PREV_CONSULTA DATE NOT NULL,
    DT_CONSUL DATE,
    VALOR NUMERIC(10, 2) NOT NULL,
    STATUS BOOLEAN NOT NULL,
    FOREIGN KEY (COD_PAC) REFERENCES PACIENTE(COD_PAC),
	FOREIGN KEY (COD_PLANO) REFERENCES PLANO(COD_PLANO),
    FOREIGN KEY (CRM) REFERENCES MEDICO(CRM)
);

CREATE TABLE PM (
    COD_PM SERIAL PRIMARY KEY,
    COD_MED INT,
    COD_PLANO INT,
    PRECO NUMERIC(10, 2) NOT NULL,
    FOREIGN KEY (COD_MED) REFERENCES MEDICAMENTO(COD_MED),
    FOREIGN KEY (COD_PLANO) REFERENCES PLANO(COD_PLANO)
);

CREATE TABLE APARTAMENTO (
    NUMERO INT PRIMARY KEY,
    LOCALIZACAO TEXT NOT NULL
);

CREATE TABLE INTERNACAO (
    COD_INTERNA SERIAL PRIMARY KEY,
    COD_PAC INT,
	COD_PLANO INT,
    COD_PM INT,
    CRM INT,
    NUMERO INT,
    DT_INTERNA DATE NOT NULL,
    VALOR NUMERIC(10, 2) NOT NULL,
    DT_CONCLUSAO DATE,
    MOTIVO TEXT,
    CONCLUSAO TEXT, -- ALTA OU ÓBITO
	FOREIGN KEY (COD_PLANO) REFERENCES PLANO(COD_PLANO),
    FOREIGN KEY (COD_PAC) REFERENCES PACIENTE(COD_PAC),
    FOREIGN KEY (COD_PM) REFERENCES PM(COD_PM),
    FOREIGN KEY (CRM) REFERENCES MEDICO(CRM),
    FOREIGN KEY (NUMERO) REFERENCES APARTAMENTO(NUMERO)
);
 
SELECT * FROM CONSULTA;
SELECT * FROM MEDICO;
SELECT * FROM PACIENTE;
SELECT * FROM PLANO;
DELETE FROM PACIENTE WHERE COD_PAC = 3;
SELECT REMOVER_LINHA('PLANO', '1')
SELECT INSERIR_LINHA('PLANO', 'NOME', '1.50', '2.9')
SELECT INSERIR_LINHA('MEDICO', '123', 'NOME', '1233', '123', 'RUA DOS BAÚS')
SELECT INSERIR_LINHA('CONSULTA', '3', '123', '1', 'O paciente foi traído pela mulher.', 
					 '1999-01-08', '1999-01-08', '1.50', 'TRUE');
					 (COD_PAC, CRM, COD_PLANO, MOTIVO, DT_PREV_CONSULTA, VALOR, STATUS)









