-- FUNÇÕES INSERT

CREATE OR REPLACE FUNCTION INSERIR_PAC(
    CPF TEXT,
    NOME TEXT,
    CONTATO TEXT,
    ENDERECO TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PACIENTE (CPF, NOME, CONTATO, ENDERECO)
    VALUES (CPF, NOME, CONTATO, ENDERECO);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_MEDICAMENTO(
    NOME TEXT,
    BULA TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO MEDICAMENTO (NOME, BULA)
    VALUES (NOME, BULA);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_ITEM_MED(
    COD_ITEM_MED INT,
    COD_MED INT,
    QUANTIDADE INT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO ITEM_MED (COD_ITEM_MED, COD_MED, QUANTIDADE)
    VALUES (COD_ITEM_MED, COD_MED, QUANTIDADE);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_FUNC(
    NOME TEXT,
    CPF TEXT,
    COD_CARGO INT,
    SALARIO NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO FUNCIONARIO (NOME, CPF, COD_CARGO)
    VALUES (NOME, CPF, COD_CARGO);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_CONSULTA(
    COD_PAC INT,
    CRM INT,
    COD_PLANO INT,
    MOTIVO TEXT,
    DT_PREV_CONSULTA DATE,
    VALOR NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO CONSULTA (COD_PAC, CRM, COD_PLANO, MOTIVO, DT_PREV_CONSULTA, VALOR, STATUS)
    VALUES (COD_PAC, CRM, COD_PLANO, MOTIVO, DT_PREV_CONSULTA, VALOR, TRUE);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_PROC(
    COD_FUNC INT,
    COD_SERVICO INT,
    COD_PAC INT,
    DT_ATEND DATE,
    VALOR NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PROCEDIMENTO (COD_FUNC, COD_SERVICO, COD_PAC, DT_ATEND, VALOR)
    VALUES (COD_FUNC, COD_SERVICO, COD_PAC, DT_ATEND, VALOR);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_PLANO(
    NOME TEXT,
    VALOR_CON NUMERIC,
    VALOR_INT NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PLANO (NOME, VALOR_CON, VALOR_INT)
    VALUES (NOME, VALOR_CON, VALOR_INT);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_INTERNA(
    COD_PAC INT,
    COD_PM INT,
    CRM INT,
    NUMERO INT,
    DT_INTERNA DATE,
    VALOR NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO INTERNACAO (COD_PAC, COD_PM, CRM, NUMERO, DT_INTERNA, VALOR)
    VALUES (COD_PAC, COD_PM, CRM, NUMERO, DT_INTERNA, VALOR);
END;
$$ LANGUAGE PLPGSQL;



