-- ATENDENTE

CREATE ROLE ATENDENTE WITH 
LOGIN
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOINHERIT
PASSWORD 'atendente123';

GRANT EXECUTE ON FUNCTION GERAR_FATURA_INTERNA(INT), INSERIR_LINHA(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT), 
GERAR_FATURA_CONSULTA(INT) TO ATENDENTE;

GRANT INSERT, UPDATE, SELECT ON PACIENTE, CONSULTA, INTERNACAO, PROCEDIMENTO TO ATENDENTE;
GRANT SELECT ON PLANO, ITEM_MED, PM TO ATENDENTE;

GRANT USAGE, SELECT ON SEQUENCE internacao_cod_interna_seq, paciente_cod_pac_seq, 
procedimento_cod_proced_seq, consulta_cod_consul_seq, plano_cod_plano_seq TO ATENDENTE;


SET SESSION AUTHORIZATION ATENDENTE;
-- SELECT INSERIR_LINHA('MEDICO', '123', 'DAVID', '329812398', '23901329', 'RUA JOÃO');
SELECT GERAR_FATURA_INTERNA(1);
RESET SESSION AUTHORIZATION;

SELECT * FROM CONSULTA;

-- MEDICO

CREATE ROLE MEDICO WITH 
LOGIN
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOINHERIT
PASSWORD 'medico123';

GRANT EXECUTE ON FUNCTION LIBERAR_ALTA(INT), ATUALIZAR_STATUS_CONSULTA(INT, BOOLEAN) TO MEDICO;

GRANT INSERT, UPDATE, SELECT ON PACIENTE , CONSULTA, INTERNACAO, PROCEDIMENTO TO ATENDENTE;
GRANT SELECT ON PLANO, ITEM_MED, PM TO ATENDENTE;

GRANT USAGE, SELECT ON SEQUENCE internacao_cod_interna_seq, paciente_cod_pac_seq, 
procedimento_cod_proced_seq, consulta_cod_consul_seq, plano_cod_plano_seq TO ATENDENTE;


SET SESSION AUTHORIZATION ATENDENTE;
-- SELECT INSERIR_LINHA('MEDICO', '123', 'DAVID', '329812398', '23901329', 'RUA JOÃO');
SELECT GERAR_FATURA_INTERNA(1);
RESET SESSION AUTHORIZATION;

CREATE ROLE ADMINISTRADOR WITH 
LOGIN
SUPERUSER
NOCREATEDB
CREATEROLE
NOINHERIT
PASSWORD 'admin';

GRANT SELECT ON
APARTAMENTO,
CARGO,
CONSULTA,
FUNCIONARIO,
INTERNACAO,
MEDICAMENTO,
MEDICO,
PACIENTE,
PLANO,
PM,
PROCEDIMENTO,
SUPERVISAO,
ITEM_MED
TO ADMINISTRADOR;
